### ISSUE TITLE
Unterstützer-Logos einfügen CdV Berlin

### ISSUE THREAD

**Issue by gitstief** [codingdavinci/codingdavinci.de#77]

**Comment by lucypatterson** [comment]
Hi @nosy79,
Deadline tomorrow! Hope that's ok. I looked into doing it myself but couldn't wrap my head around the various divs...

Please insert a new header "PARTNER" underneath the "VERANSTALTER" section in the same style but with no little picture above. 

Then include the following 3 logos (plus links) horizontally in this order:
[DNK logo](https://drive.google.com/file/d/0B156FtSBxGt-MExNQVJhYjJTdUU/view?usp=sharing) (with link http://www.dnk.de/)
[Sharing Heritage logo](https://drive.google.com/file/d/0B156FtSBxGt-UXhiWmNHVldYQnM/view?usp=sharing) (with link http://www.sharingheritage.de/en/main/)
[OKF logo](https://codingdavinci.de:8080/img/logos/okfn.png) (with link https://okfn.de/)

There will be further logos to include in this section from HTW & JMB, but only once the cooperation contracts are signed.

**Comment by nosy79** [comment]
No permissions for the first 2 logos on Google...

**Comment by nosy79** [comment]
should there be a small picture above the headline?
And: still one sharingheritage picture missing...
But else: Freigabe?

**Comment by lucypatterson** [comment]
Where should I be looking? It's not at https://codingdavinci.de:8080/events/berlin/
I've released the last image (sorry - shared with the wrong email address)

**Comment by nosy79** [comment]
Ok I added the second logo, too. Also had no view on the URL you wrote  - did a reload - it was there :D. Damn browser cache...
I think it does not look well if we have partner and verantstalter directly together.
Do you have an idea where the partners or verantstalter can have a better place?

**Comment by lucypatterson** [comment]
Cool. Let's remove the hands image (we already use it above Teilnehmer) and have no picture above "Partner". I think it's ok to have both Veranstalter and Partner next to each other. It's the same as [Nord](https://codingdavinci.de:8080/events/nord/). There will anyway be more logos to come.

The only problem is with responsiveness. We need the columns to float underneath each other rather than remain side-by-side. The code for this must be in the Nord version of the page. If you have time to fix this today, please do, otherwise, make the small changes above and merge. We can fix responsiveness later.

Thanks!
