### ISSUE TITLE
Veranstalter-Logos einfügen CdV Berlin

### ISSUE THREAD

**Issue by gitstief** [codingdavinci/codingdavinci.de#78]

**Comment by nosy79** [comment]
Was soll ich wo einfügen?

**Comment by lucypatterson** [comment]
Page doesn't exist yet... will be the Berlin equivalent of Hamburg's https://codingdavinci.de/events/#hosts

**Comment by nosy79** [comment]
Is it still clear which logos will be used?

**Comment by anjadigis** [comment]
digiS-Logi ist aktuell

**Comment by lucypatterson** [comment]
DDB digiS WMDE OKF 

@fischerdata in this order? (and if so, should we also change the order for the footer and 'über uns' page?)

**Comment by gitstief** [comment]
Unser Logo [ddb.png](https://github.com/codingdavinci/codingdavinci.de/blob/gh-pages/img/logos/ddb.png) ist auch noch aktuell. Ich kann jederzeit eine größere Version liefern, falls nötig.

**Comment by anjadigis** [comment]
this was the order of appearance :) **D**DB, **o**pen Knowledge foundation, **s**ervicestelle digitalisierung, **w**ikimedia

**Comment by lucypatterson** [comment]
Confirmed. The order is DDB, OKF, digiS, WMDE

**Comment by nosy79** [comment]
ich hab das erstmal in den branch 17-4-events gepackt, ich merge das wenn ich sonst weiss wie die events-seite aussieht und dass ich sie gut finde.

**Comment by nosy79** [comment]
Die Events-Seite ist meines Wissens nach erstmal soweit vollständig, man kann das also in der Vorschau ansehen.

**Comment by lucypatterson** [comment]
Hi @nosy79 

A few corrections based on comparison with http://web.archive.org/web/20160814005440/https://codingdavinci.de/events/:
- Please implement the relevant illustrations above all h2 titles, e.g. here:
![screen shot 2017-04-16 at 17 20 26](https://cloud.githubusercontent.com/assets/11370940/25072207/077d7522-22c9-11e7-8724-5f202c3f42ff.png)
- Please increase space between h2 titles and body text (as here https://codingdavinci.de/events/)
- Please use green accent colour for "Berlin" in the first h2 heading
- Please implement responsive width for body text as https://codingdavinci.de/events/
- Using the timeline graphic is good here (rather than Kasten), but please correct the text (**Kick-Off**
21./22. Oktober, Hochschule für Technik und Wirtschaft | **Sprint** 6 Wochen Zeit, um kooperativ Projekte umzusetzen | **Preisverleihung** 2. Dezember, Ort wird bald bekanntgegeben)
- Under "Programme", the layout of the Kasten text should be as below:
![screen shot 2017-04-16 at 17 40 10](https://cloud.githubusercontent.com/assets/11370940/25072337/c908cd8e-22cb-11e7-9c1c-6690aafd8bf6.png)

Thanks!
Lucy

**Comment by lucypatterson** [comment]
I have to admit, it's strange to see the logos duplicated so close to the footer like that. Let's see what @fischerdata, @anjadigis, and @gitstief think. In any case, it would be good if they were justified to the center, rather than to the left.

**Comment by lucypatterson** [comment]
@nosy79 please remove the OKF logo, and justify the remaining three to the centre. 
Thanks!

**Comment by nosy79** [comment]
Guess it is already done
